### ISSUE TITLE
Caused by: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

### ISSUE THREAD

**Issue by ashishguptasanu** [ernestoyaquello/VerticalStepperForm#66]
mySteps = new String[]{"Test Name", "Marks Obtained", "Total Marks", "Date"};
        int colorPrimary = ContextCompat.getColor(getApplicationContext(), R.color.colorPrimary);
        int colorPrimaryDark = ContextCompat.getColor(getApplicationContext(), R.color.colorPrimaryDark);

        VerticalStepperFormLayout verticalStepperForm =  (VerticalStepperFormLayout)findViewById(R.id.vertical_stepper_form);

        // Setting up and initializing the form
        VerticalStepperFormLayout.Builder.newInstance(verticalStepperForm, mySteps, this, this)
                .primaryColor(colorPrimary)
                .primaryDarkColor(colorPrimaryDark)
                .displayBottomNavigation(false) // It is true by default, so in this case this line is not necessary
                .init();

I am getting the error on  the last line.

> E/AndroidRuntime: FATAL EXCEPTION: main
    Process: volunteer.upay.com.upay, PID: 7053
    java.lang.RuntimeException: Unable to start activity ComponentInfo{volunteer.upay.com.upay/volunteer.upay.com.upay.Activities.AddStudentMarks}: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.view.ViewGroup.addViewInner(ViewGroup.java:3936)
        at android.view.ViewGroup.addView(ViewGroup.java:3786)
        at android.view.ViewGroup.addView(ViewGroup.java:3727)
        at android.view.ViewGroup.addView(ViewGroup.java:3700)
        at ernestoyaquello.com.verticalstepperform.VerticalStepperFormLayout.setUpStep(VerticalStepperFormLayout.java:557)
        at ernestoyaquello.com.verticalstepperform.VerticalStepperFormLayout.setUpSteps(VerticalStepperFormLayout.java:546)
        at ernestoyaquello.com.verticalstepperform.VerticalStepperFormLayout.initializeForm(VerticalStepperFormLayout.java:512)
        at ernestoyaquello.com.verticalstepperform.VerticalStepperFormLayout.initStepperForm(VerticalStepperFormLayout.java:487)
        at ernestoyaquello.com.verticalstepperform.VerticalStepperFormLayout.initialiseVerticalStepperForm(VerticalStepperFormLayout.java:474)
        at ernestoyaquello.com.verticalstepperform.VerticalStepperFormLayout$Builder.init(VerticalStepperFormLayout.java:1239)
        at volunteer.upay.com.upay.Activities.AddStudentMarks.onCreate(AddStudentMarks.java:40)
        at android.app.Activity.performCreate(Activity.java:5990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
        at android.app.ActivityThread.access$800(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5254) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by SamamaBukhari** [comment]
Did you find the solution? Kindly post it here.

**Comment by ernestoyaquello** [comment]
First of all, sorry for the immense delay in my response; after a long period of abandonment it is only recently that I have found the time to work on this library again.

Regarding the issue, this only happens if you provide a step layout with a parent already set, which is illegal. For example, this code would cause the exception:
```java
daysStepContent = inflater.inflate(R.layout.step_days_of_week_layout, parentView, true);
```

While this one wouldn't:
```java
daysStepContent = inflater.inflate(R.layout.step_days_of_week_layout, null, false);
```

I hope that this information, even though delivered late, can be of help.
